### ISSUE TITLE
Support for gcc8 and gcov8 

### ISSUE THREAD

**Issue by theShmoo** [JacquesLucke/gcov-viewer#8]
Is it planned to support gcc8 and gcov8?

**Comment by JacquesLucke** [comment]
I do not plan to implement it. Afaik only since gcov9 it supports outputting the coverage data in json format, which makes it much easier to parse for this extension.

If someone else wants to figure out how to get this working with an older compiler version, please go ahead and make a pull request.

**Comment by theShmoo** [comment]
Thanks!

**Comment by GitMensch** [comment]
see #14 for a workaround (python script to be configured as gcov binary, which internally converts gcov output into json format enabling this extension to read it).
